### ISSUE TITLE
Got error when installing riscv-qemu

### ISSUE THREAD

**Issue by bale-john** [riscv/riscv-qemu#11]
Hi,
    I installed riscv-qemu as README.md. When I do "make" I got this error:

    /root/riscv-qemu/hw/riscv/htif/htif.c:176:9: error: format ‘%lx’ expects argument of type ‘long unsigned int’, but argument 2 has type ‘hwaddr’ [-Werror=format=]
         printf("Invalid htif register address %016lx\n", (uint64_t)addr);

   After i commented it, i got new error:

    /root/riscv-qemu/target-riscv/op_helper.c:482:34: error: expected ‘)’ before ‘a’
     return (int64_t)((__int128_t)a*b >> 64);
    /root/riscv-qemu/target-riscv/op_helper.c:481:14: error: unused variable ‘b’ [-Werror=unused-variable]
     uint64_t b = arg2;
    /root/riscv-qemu/target-riscv/op_helper.c:480:13: error: unused variable ‘a’ [-Werror=unused-variable]
     int64_t a = arg1;

   My os is: ubuntu 3.19.0-15-generic. My compiler is gcc-4.9.2
   I will really appreciate it if you can offer some help!

**Comment by sagark** [comment]
Looking at the recent commit history of qemu upstream, it's unlikely to compile with gcc-4.9+ even with the RISC-V specific portions of the code updated. If you need to use this as-is, I'd use gcc-4.8.

Updating riscv-qemu to support the new privileged spec is still a to-do - when we do that, we'll probably also rebase in order to pull in the upstream changes for gcc-4.9+ support.
